In [1]:
import pandas  as pd
import numpy as  np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
oneDarray=np.array([1,2,3,4,5,6])
print(oneDarray)

[1 2 3 4 5 6]


In [3]:
twoDarray=np.array([[1,2,3,4,5,6],[9,8,3,7,5,6]])
print(twoDarray)

[[1 2 3 4 5 6]
 [9 8 3 7 5 6]]


In [4]:
threeDarray=np.array([[[1,2,3,4,5,6],[9,8,3,7,5,6]],[[1,2,3,4,5,6],[9,8,3,7,5,6]]])
print(threeDarray)

[[[1 2 3 4 5 6]
  [9 8 3 7 5 6]]

 [[1 2 3 4 5 6]
  [9 8 3 7 5 6]]]


In [5]:
print(oneDarray.ndim)
print(twoDarray.ndim)
print(threeDarray.ndim)

1
2
3


In [6]:
print(twoDarray[1,0])
print(twoDarray[1])


9
[9 8 3 7 5 6]


In [7]:
print(twoDarray[1,1:4])

[8 3 7]


In [8]:
twoDarray[1,2]=24
print(twoDarray)

[[ 1  2  3  4  5  6]
 [ 9  8 24  7  5  6]]


In [9]:
print(threeDarray[0,1])

[9 8 3 7 5 6]


In [10]:
print(threeDarray[0,1,2])

3


In [11]:
print(oneDarray.shape)
print(twoDarray.shape)
print(threeDarray.shape)

(6,)
(2, 6)
(2, 2, 6)


In [12]:
print(twoDarray.shape)

(2, 6)


In [13]:
for i in twoDarray:
  for j in i:
    print(j)

1
2
3
4
5
6
9
8
24
7
5
6


In [14]:
for i in threeDarray:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
9
8
3
7
5
6
1
2
3
4
5
6
9
8
3
7
5
6


In [15]:
zerosArray = np.zeros(5)
zerosArray

array([0., 0., 0., 0., 0.])

In [16]:
zerosArray=zerosArray.astype(int)
zerosArray

array([0, 0, 0, 0, 0])

In [17]:
onesArray=np.ones(10)
onesArray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
onesArray=onesArray.astype(int)
onesArray

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
predefineArray=np.full(10,31)
predefineArray

array([31, 31, 31, 31, 31, 31, 31, 31, 31, 31])

In [20]:
Matrix=np.array([[1,2,3],[4,5,6]])
Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
Pythonlist=[[1,2,3],[4,5,6]]
Pythonlist

[[1, 2, 3], [4, 5, 6]]

In [22]:
print(Matrix+2) #Increment  2 with each elements

[[3 4 5]
 [6 7 8]]


In [23]:
print(Matrix-2) #Decrement  2 with each elements

[[-1  0  1]
 [ 2  3  4]]


In [24]:
print(Matrix*2) #Multiply  2 with each elements

[[ 2  4  6]
 [ 8 10 12]]


In [25]:
print(Pythonlist*2)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]


In [26]:
print(Matrix**2) #Square  with each elements

[[ 1  4  9]
 [16 25 36]]


In [27]:
print(Matrix/2) #Divide  2 with each elements

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [28]:
print(Matrix//2) #Divide  2 with each elements

[[0 1 1]
 [2 2 3]]


In [30]:
print(Matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
Matrix1=np.array([[-1,-2,-3],[-4,-5,-6]])
Matrix1

array([[-1, -2, -3],
       [-4, -5, -6]])

In [32]:
Pythonlist1=[[-1,-2,-3],[-4,-5,-6]]
Pythonlist1

[[-1, -2, -3], [-4, -5, -6]]

In [33]:
print(Matrix+Matrix1)

[[0 0 0]
 [0 0 0]]


In [34]:
print(Pythonlist+Pythonlist1)

[[1, 2, 3], [4, 5, 6], [-1, -2, -3], [-4, -5, -6]]


In [35]:
print(Matrix-Matrix1)

[[ 2  4  6]
 [ 8 10 12]]


In [37]:
print(Matrix*Matrix1)

[[ -1  -4  -9]
 [-16 -25 -36]]


In [38]:
print(Matrix/Matrix1)

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [40]:
Mat=np.array([[1,2,3],[3,4,3],[5,6,3]])
Mat

array([[1, 2, 3],
       [3, 4, 3],
       [5, 6, 3]])

In [41]:
Mat1=np.array([[1,2,2],[3,2,4],[2,5,6]])
Mat

array([[1, 2, 3],
       [3, 4, 3],
       [5, 6, 3]])

In [42]:
np.matmul(Mat,Mat1)

array([[13, 21, 28],
       [21, 29, 40],
       [29, 37, 52]])

In [45]:
np.min(Mat)
np.max(Mat)

6

In [44]:
np.sum(Mat)

30

In [46]:
np.std(Mat)

1.4142135623730951

In [47]:
np.mean(Mat)

3.3333333333333335

In [48]:
np.median(Mat)

3.0